#!/bin/bash
set -euo pipefail

# =========================================================================
# Kōan Docker Setup — Auto-detect host binaries and generate mounts
# =========================================================================
# This script inspects the host system to find CLI binaries (claude, gh,
# copilot, ollama) and their dependencies (Node.js runtime for Claude),
# then generates a docker-compose.override.yml with the correct volume
# mounts.
#
# Usage:
#   ./setup-docker.sh           # Auto-detect and generate
#   ./setup-docker.sh --dry-run # Show what would be mounted without writing
# =========================================================================

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
    DRY_RUN=true
fi

OVERRIDE_FILE="docker-compose.override.yml"

# --- ANSI Colors (disabled when stdout is not a TTY) ---
if [ -n "${KOAN_FORCE_COLOR:-}" ] || [ -t 1 ]; then
    BOLD='\033[1m' DIM='\033[2m'
    RED='\033[31m' GREEN='\033[32m' YELLOW='\033[33m' CYAN='\033[36m'
    RESET='\033[0m'
else
    BOLD='' DIM='' RED='' GREEN='' YELLOW='' CYAN='' RESET=''
fi

log()     { printf "${DIM}[setup-docker]${RESET} %s\n" "$*"; }
warn()    { printf "${YELLOW}[setup-docker] ⚠ %s${RESET}\n" "$*" >&2; }
error()   { printf "${RED}[setup-docker] ✗ %s${RESET}\n" "$*" >&2; }
success() { printf "${GREEN}[setup-docker] ✓ %s${RESET}\n" "$*"; }
section() { printf "\n${BOLD}${CYAN}--- %s ---${RESET}\n" "$*"; }

# -------------------------------------------------------------------------
# Detect binaries and their real paths (resolve symlinks)
# -------------------------------------------------------------------------
declare -a VOLUME_MOUNTS=()
declare -a FOUND_BINS=()

detect_binary() {
    local name="$1"
    local target="/host-bin/$name"

    local path
    path=$(command -v "$name" 2>/dev/null || true)
    if [ -z "$path" ]; then
        return 1
    fi

    # Resolve symlinks to get the real binary
    local real_path
    real_path=$(realpath "$path" 2>/dev/null || readlink -f "$path" 2>/dev/null || echo "$path")

    success "Found $name: $real_path"
    VOLUME_MOUNTS+=("      - ${real_path}:${target}:ro")
    FOUND_BINS+=("$name")
    return 0
}

# Detect a directory if it exists
detect_dir() {
    local host_dir="$1"
    local container_dir="$2"
    local mode="${3:-ro}"
    local label="${4:-$host_dir}"

    # Expand ~ to $HOME
    local expanded="${host_dir/#\~/$HOME}"

    if [ -d "$expanded" ]; then
        success "Found $label: $expanded"
        VOLUME_MOUNTS+=("      - ${expanded}:${container_dir}:${mode}")
        return 0
    fi
    return 1
}

# Node.js and gh are installed in the Docker image — no host mounts needed.

# -------------------------------------------------------------------------
# Detect host UID/GID
# -------------------------------------------------------------------------
detect_uid_gid() {
    local uid gid
    uid=$(id -u)
    gid=$(id -g)
    log "Host user: UID=$uid GID=$gid"
    echo "HOST_UID=$uid" > .env.docker
    echo "HOST_GID=$gid" >> .env.docker
}

# -------------------------------------------------------------------------
# Resolve workspace symlinks for Docker bind mounts
# -------------------------------------------------------------------------
resolve_workspace() {
    if [ ! -d "workspace" ]; then
        log "No workspace/ directory — skipping project mount resolution"
        return
    fi

    local count=0
    for entry in workspace/*/; do
        [ -d "$entry" ] || continue
        local name
        name=$(basename "$entry")

        if [ -L "workspace/$name" ]; then
            local target
            target=$(realpath "workspace/$name")
            log "Workspace symlink: $name → $target"
            # Symlinks need explicit bind mounts since Docker doesn't follow them
            VOLUME_MOUNTS+=("      - ${target}:/app/workspace/${name}")
            count=$((count + 1))
        fi
    done

    if [ $count -gt 0 ]; then
        success "Resolved $count workspace symlink(s)"
    fi
}

# -------------------------------------------------------------------------
# Generate docker-compose.override.yml
# -------------------------------------------------------------------------
generate_override() {
    if [ ${#VOLUME_MOUNTS[@]} -eq 0 ]; then
        warn "No volume mounts detected — override file will be minimal"
    fi

    local content
    content="# Auto-generated by setup-docker.sh — $(date -Iseconds)
# Re-run ./setup-docker.sh if you change your CLI tools or workspace layout.
#
# Binary mounts: ${#FOUND_BINS[@]} CLI tool(s) detected
# This file is gitignored.

services:
  koan:
    build:
      args:
        HOST_UID: \${HOST_UID:-$(id -u)}
        HOST_GID: \${HOST_GID:-$(id -g)}
    volumes:"

    for mount in "${VOLUME_MOUNTS[@]}"; do
        content="$content
$mount"
    done

    if [ "$DRY_RUN" = true ]; then
        printf "\n${BOLD}${CYAN}=== Would write to %s ===${RESET}\n" "$OVERRIDE_FILE"
        echo "$content"
        printf "${BOLD}${CYAN}=== End ===${RESET}\n"
    else
        echo "$content" > "$OVERRIDE_FILE"
        success "Written: $OVERRIDE_FILE"
    fi
}

# =========================================================================
# Main
# =========================================================================

log "Detecting host environment..."

# 1. CLI binaries (only Claude CLI needs host mount — git, gh, node are in the image)
section "CLI Binaries"
detect_binary "claude" || warn "claude not found — agent loop will not work"

# 2. Auth directories
section "Auth Directories"
detect_dir "~/.claude" "/home/koan/.claude" "rw" "Claude auth" || \
    log "~/.claude not found (ok if using ANTHROPIC_API_KEY)"

detect_dir "~/.copilot" "/home/koan/.copilot" "rw" "Copilot auth" || \
    log "~/.copilot not found (ok if not using Copilot)"

detect_dir "~/.config/gh" "/home/koan/.config/gh" "ro" "GitHub CLI auth" || \
    warn "~/.config/gh not found — gh CLI won't be authenticated"

detect_dir "~/.gitconfig" "/home/koan/.gitconfig" "ro" "Git config" || true

# 3. Workspace symlink resolution + projects.yaml
section "Workspace"
resolve_workspace

# 3b. Ensure projects.docker.yaml exists
if [ ! -f "projects.docker.yaml" ]; then
    if [ -f "projects.example.yaml" ]; then
        success "Created projects.docker.yaml from example template"
        sed '/^projects:/,$d' projects.example.yaml > projects.docker.yaml
    fi
else
    success "Found projects.docker.yaml"
fi
VOLUME_MOUNTS+=("      - ./projects.docker.yaml:/app/projects.yaml")

# 4. Generate files
section "Generating"
detect_uid_gid
generate_override

if [ "$DRY_RUN" = false ]; then
    printf "\n${BOLD}${CYAN}╭──────────────────────────────────────────────────────────╮${RESET}\n"
    printf "${BOLD}${CYAN}│${RESET} ${GREEN}✓ Setup complete!${RESET}                                        ${BOLD}${CYAN}│${RESET}\n"
    printf "${BOLD}${CYAN}├──────────────────────────────────────────────────────────┤${RESET}\n"
    printf "${BOLD}${CYAN}│${RESET}  1. Review %-43s ${BOLD}${CYAN}│${RESET}\n" "$OVERRIDE_FILE"
    printf "${BOLD}${CYAN}│${RESET}  2. Ensure .env has messaging credentials                ${BOLD}${CYAN}│${RESET}\n"
    printf "${BOLD}${CYAN}│${RESET}  3. docker compose up --build                            ${BOLD}${CYAN}│${RESET}\n"
    printf "${BOLD}${CYAN}╰──────────────────────────────────────────────────────────╯${RESET}\n"
fi
