#!/bin/bash
set -euo pipefail

# =========================================================================
# Kōan Docker Setup — Auto-detect host auth and generate mounts
# =========================================================================
# This script inspects the host system to find auth directories (gh, copilot)
# and workspace layout, then generates a docker-compose.override.yml with
# the correct volume mounts.
#
# Claude CLI is installed in the Docker image via npm — no host mount needed.
# Auth: ANTHROPIC_API_KEY in .env (API billing) or interactive login (subscription).
#
# Usage:
#   ./setup-docker.sh           # Auto-detect and generate
#   ./setup-docker.sh --dry-run # Show what would be mounted without writing
# =========================================================================

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
    DRY_RUN=true
fi

OVERRIDE_FILE="docker-compose.override.yml"

# --- ANSI Colors (disabled when stdout is not a TTY) ---
if [ -n "${KOAN_FORCE_COLOR:-}" ] || [ -t 1 ]; then
    BOLD='\033[1m' DIM='\033[2m'
    RED='\033[31m' GREEN='\033[32m' YELLOW='\033[33m' CYAN='\033[36m'
    RESET='\033[0m'
else
    BOLD='' DIM='' RED='' GREEN='' YELLOW='' CYAN='' RESET=''
fi

log()     { printf "${DIM}[setup-docker]${RESET} %s\n" "$*"; }
warn()    { printf "${YELLOW}[setup-docker] ⚠ %s${RESET}\n" "$*" >&2; }
error()   { printf "${RED}[setup-docker] ✗ %s${RESET}\n" "$*" >&2; }
success() { printf "${GREEN}[setup-docker] ✓ %s${RESET}\n" "$*"; }
section() { printf "\n${BOLD}${CYAN}--- %s ---${RESET}\n" "$*"; }

# -------------------------------------------------------------------------
# Detect binaries and their real paths (resolve symlinks)
# -------------------------------------------------------------------------
declare -a VOLUME_MOUNTS=()
declare -a FOUND_BINS=()

detect_binary() {
    local name="$1"
    local target="/host-bin/$name"

    local path
    path=$(command -v "$name" 2>/dev/null || true)
    if [ -z "$path" ]; then
        return 1
    fi

    # Resolve symlinks to get the real binary
    local real_path
    real_path=$(realpath "$path" 2>/dev/null || readlink -f "$path" 2>/dev/null || echo "$path")

    success "Found $name: $real_path"
    VOLUME_MOUNTS+=("      - ${real_path}:${target}:ro")
    FOUND_BINS+=("$name")
    return 0
}

# Detect a directory if it exists
detect_dir() {
    local host_dir="$1"
    local container_dir="$2"
    local mode="${3:-ro}"
    local label="${4:-$host_dir}"

    # Expand ~ to $HOME
    local expanded="${host_dir/#\~/$HOME}"

    if [ -d "$expanded" ]; then
        success "Found $label: $expanded"
        VOLUME_MOUNTS+=("      - ${expanded}:${container_dir}:${mode}")
        return 0
    fi
    return 1
}

# Node.js and gh are installed in the Docker image — no host mounts needed.

# -------------------------------------------------------------------------
# Detect host UID/GID
# -------------------------------------------------------------------------
detect_uid_gid() {
    local uid gid
    uid=$(id -u)
    gid=$(id -g)
    log "Host user: UID=$uid GID=$gid"
    echo "HOST_UID=$uid" > .env.docker
    echo "HOST_GID=$gid" >> .env.docker
}

# -------------------------------------------------------------------------
# Resolve workspace symlinks for Docker bind mounts
# -------------------------------------------------------------------------
resolve_workspace() {
    if [ ! -d "workspace" ]; then
        log "No workspace/ directory — skipping project mount resolution"
        return
    fi

    local count=0
    for entry in workspace/*/; do
        [ -d "$entry" ] || continue
        local name
        name=$(basename "$entry")

        if [ -L "workspace/$name" ]; then
            local target
            target=$(realpath "workspace/$name")
            log "Workspace symlink: $name → $target"
            # Symlinks need explicit bind mounts since Docker doesn't follow them
            VOLUME_MOUNTS+=("      - ${target}:/app/workspace/${name}")
            count=$((count + 1))
        fi
    done

    if [ $count -gt 0 ]; then
        success "Resolved $count workspace symlink(s)"
    fi
}

# -------------------------------------------------------------------------
# Generate docker-compose.override.yml
# -------------------------------------------------------------------------
generate_override() {
    if [ ${#VOLUME_MOUNTS[@]} -eq 0 ]; then
        warn "No volume mounts detected — override file will be minimal"
    fi

    local content
    content="# Auto-generated by setup-docker.sh — $(date -Iseconds)
# Re-run ./setup-docker.sh if you change your workspace layout.
# This file is gitignored.

services:
  koan:
    build:
      args:
        HOST_UID: \${HOST_UID:-$(id -u)}
        HOST_GID: \${HOST_GID:-$(id -g)}
    volumes:"

    for mount in "${VOLUME_MOUNTS[@]}"; do
        content="$content
$mount"
    done

    if [ "$DRY_RUN" = true ]; then
        printf "\n${BOLD}${CYAN}=== Would write to %s ===${RESET}\n" "$OVERRIDE_FILE"
        echo "$content"
        printf "${BOLD}${CYAN}=== End ===${RESET}\n"
    else
        echo "$content" > "$OVERRIDE_FILE"
        success "Written: $OVERRIDE_FILE"
    fi
}

# =========================================================================
# Main
# =========================================================================

log "Detecting host environment..."

# 1. Auth directories (Claude CLI is installed in the image — no host mount needed)
section "Auth Directories"
log "Claude CLI: installed in Docker image via npm"
log "  Auth option 1: ANTHROPIC_API_KEY in .env (API billing)"
log "  Auth option 2: docker compose run --rm -it koan auth (subscription login)"

# Create claude-auth/ for interactive login persistence
if [ ! -d "claude-auth" ]; then
    mkdir -p "claude-auth"
    success "Created claude-auth/ (persistent auth state for Claude CLI)"
else
    success "Found claude-auth/"
fi
VOLUME_MOUNTS+=("      - ./claude-auth:/home/koan/.claude:rw")

detect_dir "~/.copilot" "/home/koan/.copilot" "rw" "Copilot auth" || \
    log "~/.copilot not found (ok if not using Copilot)"

detect_dir "~/.config/gh" "/home/koan/.config/gh" "ro" "GitHub CLI auth" || \
    warn "~/.config/gh not found — gh CLI won't be authenticated"

detect_dir "~/.gitconfig" "/home/koan/.gitconfig" "ro" "Git config" || true

# 2. Workspace symlink resolution + projects.yaml
section "Workspace"
resolve_workspace

# 2b. Ensure missions.docker.md exists (isolated mission queue for container)
if [ ! -f "instance/missions.docker.md" ]; then
    touch "instance/missions.docker.md"
    success "Created instance/missions.docker.md (empty mission queue for container)"
else
    success "Found instance/missions.docker.md"
fi

# 2c. Generate projects.docker.yaml with workspace entries
generate_projects_yaml() {
    local yaml_file="projects.docker.yaml"

    if [ -f "$yaml_file" ]; then
        # Keep existing file if it already has project entries
        if grep -q '^projects:' "$yaml_file" && grep -qE '^  [a-zA-Z]' "$yaml_file"; then
            success "Found $yaml_file with project entries"
            return
        fi
    fi

    # Build from scratch with workspace entries
    local content="defaults:
  git_auto_merge:
    enabled: false
    base_branch: \"main\"
    strategy: \"squash\"
  max_open_prs: 10

projects:"

    local count=0
    for entry in workspace/*/; do
        [ -d "$entry" ] || continue
        local name
        name=$(basename "$entry")
        content="$content
  $name:
    path: /app/workspace/$name"
        count=$((count + 1))
    done

    if [ $count -eq 0 ]; then
        warn "No workspace projects found — projects.docker.yaml will have no entries"
        content="$content
  # Add your projects here:
  # myproject:
  #   path: /app/workspace/myproject"
    fi

    echo "$content" > "$yaml_file"
    success "Generated $yaml_file with $count workspace project(s)"
}

generate_projects_yaml
VOLUME_MOUNTS+=("      - ./projects.docker.yaml:/app/projects.yaml")

# 3. Generate files
section "Generating"
detect_uid_gid
generate_override

if [ "$DRY_RUN" = false ]; then
    printf "\n${BOLD}${CYAN}╭──────────────────────────────────────────────────────────╮${RESET}\n"
    printf "${BOLD}${CYAN}│${RESET} ${GREEN}✓ Setup complete!${RESET}                                        ${BOLD}${CYAN}│${RESET}\n"
    printf "${BOLD}${CYAN}├──────────────────────────────────────────────────────────┤${RESET}\n"
    printf "${BOLD}${CYAN}│${RESET}  1. Review %-43s ${BOLD}${CYAN}│${RESET}\n" "$OVERRIDE_FILE"
    printf "${BOLD}${CYAN}│${RESET}  2. Auth (pick one):                                     ${BOLD}${CYAN}│${RESET}\n"
    printf "${BOLD}${CYAN}│${RESET}     a. Set ANTHROPIC_API_KEY in .env (API billing)        ${BOLD}${CYAN}│${RESET}\n"
    printf "${BOLD}${CYAN}│${RESET}     b. docker compose run --rm -it koan auth (sub login)  ${BOLD}${CYAN}│${RESET}\n"
    printf "${BOLD}${CYAN}│${RESET}  3. docker compose up --build                            ${BOLD}${CYAN}│${RESET}\n"
    printf "${BOLD}${CYAN}╰──────────────────────────────────────────────────────────╯${RESET}\n"
fi
